#!/bin/sh

echo "Generating README"

# https://github.com/fivestar/mdtree
tree -tf --noreport -I '*~' --charset ascii $1 |
       sed -e 's/| \+/  /g' -e 's/[|`]-\+/ */g' -e 's:\(* \)\(\(.*/\)\([^/]\+\)\):\1[\4](\2):g'  -e 's/.cpp//g'> README.md
